name: Regression End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
      with:
        node-version: 14
      
      - name: Run Cypress tests
        run: npm run cypress:run
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests

      - name: Cleanup
      run: npm run cypress:cleanup
      # - name: Cypress run
      #   uses: cypress-io/github-action@v6